FROM mcr.microsoft.com/devcontainers/base:focal

# Install Node.js using apt-get
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends nodejs npm